Glenn updates
Azure-Samples/functions-quickstart-python-http-azd pull request #7
Opened 2024-08-27 20:24 UTC by ggailey777

2024-08-27 20:46 UTC, paulyuk requested changes
LGTM, tiny suggestion

2024-08-27 20:46 UTC, paulyuk commented on test.http
> +GET http://localhost:7071/api/httpget?name=Awesome%20Developer HTTP/1.1
```suggestion
GET http://localhost:7071/api/httpget?name=World HTTP/1.1
```

2024-08-28 20:19 UTC, paulyuk requested changes
Just a few comments

2024-08-28 20:19 UTC, paulyuk commented on README.md
> +You can download this project template in one of these ways:
I like this but I think it's making it a little too long.  I would show only 1 or possibly 2 methods.  To me either azd init (no git) or fork and clone.

2024-08-28 20:19 UTC, paulyuk commented on README.md
> +    pip install -r requirements.txt
```suggestion
    pip3 install -r requirements.txt
```

pip3 and python3 work better multi plat.  pip and python only aliases work best on only Windows.

2024-08-28 20:54 UTC, ggailey777 commented on README.md
> +
```suggestion
```

2024-08-28 23:39 UTC, paulyuk approved these changes
LGTM.  thank you @ggailey777

2024-08-28 23:39 UTC, merged