minor tweaks
Azure-Samples/functions-quickstart-python-http-azd pull request #8
Opened 2024-08-28 00:36 UTC by BigMorty

Update Readme and azure.yaml

2024-08-28 01:22 UTC, ggailey777 approved these changes

2024-08-28 01:22 UTC, ggailey777 commented on README.md
> +#### bash
I think that my original docs on this are incorrect and the tabs should be `Windows | Linux/macOs` but I'll fix this when update readmes (and in the regular Python quickstart too).

2024-08-28 01:27 UTC, paulyuk approved these changes
LGTM

2024-08-28 03:43 UTC, ggailey777 requested changes
The change doesn't actually work on a Windows command prompt

2024-08-28 03:43 UTC, ggailey777 commented on README.md
> +.venv/scripts/activate
Both ways work on Windows PowerShell

2024-08-28 03:43 UTC, ggailey777 commented on README.md
> +.venv/scripts/activate
This change doesn't work on Windows command prompt. Can you please revert it?

2024-08-28 03:44 UTC, ggailey777 commented on README.md
> +.venv/scripts/activate
OK, I'll definitely be fixing our docs, which I think is the source of this confusion 🙄

2024-08-28 23:39 UTC, merged

2024-08-29 00:33 UTC, paulyuk reviewed
LGTM